server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam_online?serverTimezone=UTC
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      # 每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新
      ddl-auto: update
    properties:
      hibernate:
        # 懒加载
        enable_lazy_load_no_trans: true

# 人脸识别
config:
  arcface-sdk:
    sdk-lib-path: d:/arcsoft_lib
    app-id: EqUBNAaUpPGT5da8NZ7aKC2wjHQgnxjJGPaJuWSpnw4b
    sdk-key: HH52Lrh1UsV5yDVyPkNHWUUpr4AG4Vn7vLSfRRddz13f
    thread-pool-size: 5
    # 人脸相似预期值，认为只要相似度大于该值就是同一个人
    pass-rate: 70
